version: '2'
services:
  keeweb:
    build: .
    image: jonifen/keeweb
    container_name: keeweb
    networks:
      keeweb_net:
        ipv4_address: 172.23.0.2
    ports:
      - '80:80/tcp'
    restart: unless-stopped