version: '3.7'

networks:
  keeweb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  keeweb:
    build: .
    image: jonifen/keeweb
    container_name: keeweb
    networks:
      keeweb_net:
        ipv4_address: 172.23.0.5
    # ports:
    #   - '9008:80/tcp'
    expose:
      - 80
    restart: unless-stopped